### ISSUE TITLE
20200722 レビューコメント

### ISSUE THREAD

**Issue by yoship1972** [nablarch-development-standards/nablarch-style-guide#11]
- 画面イメージは英語版に差し替える必要はないか？

　　https://github.com/nablarch-development-standards/nablarch-style-guide/blob/feature-NAB-356/en/java/staticanalysis/checkstyle/docs/Jenkins-settings.md
　　https://github.com/nablarch-development-standards/nablarch-style-guide/blob/feature-NAB-356/en/java/staticanalysis/spotbugs/docs/Jenkins-settings.md

**Comment by asaina13** [comment]
画像の差し替えに関しては以下の理由から不要と判断しました。
・社外製品（Jenkins）の操作画面の画像で対応するには英語版のJenkinsの用意が必要なため
・操作画面が日英で異なるわけではないので英語版に訳さずとも通じるため

**Comment by yoship1972** [comment]
>操作画面が日英で異なるわけではないので英語版に訳さずとも通じるため

すべての説明がそうとも限らないが、問題箇所は公開後に対応する、と割り切り、ここではOKとする。
